### ISSUE TITLE
file exists and is identical to local copy

### ISSUE THREAD

**Issue by pahud** [alex-phillips/node-clouddrive#20]
I got some messages like this and I believe this is due to same MD5 checksum of files in different local directories.

Yes I probably save two copies in different local directories but I need to keep my local dir sync to remote dir. Can I just force it upload anyway?

```
Failed to upload file '/o/folders/Emilie/1T-black/16045432646_5334066e3d_o.jpg': File 'Emilie/1T-black/16045432646_5334066e3d_o.jpg' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/16070534152_20714975ac_o.jpg': File 'Emilie/1T-black/16070534152_20714975ac_o.jpg' exists and is identical to local copy
```

**Comment by alex-phillips** [comment]
@pahud, there is a config option (`clouddrive config`) that allows duplicates remotely. Use `clouddrive config upload.duplicates true`.

**Comment by pahud** [comment]
thank you!

then I got this error

```
# clouddrive upload -o /o/folders/Emilie /
Failed to upload file '/o/folders/Emilie/1T-black/.DocumentRevisions-V100/.cs/ChunkStoreDatabase': File 'Emilie/1T-black/.DocumentRevisions-V100/.cs/ChunkStoreDatabase' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.DocumentRevisions-V100/.cs/ChunkStoreDatabase-wal': File 'Emilie/1T-black/.DocumentRevisions-V100/.cs/ChunkStoreDatabase-wal' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.DocumentRevisions-V100/LibraryStatus': File 'Emilie/1T-black/.DocumentRevisions-V100/LibraryStatus' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.DocumentRevisions-V100/db-V1/db.sqlite': File 'Emilie/1T-black/.DocumentRevisions-V100/db-V1/db.sqlite' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.DocumentRevisions-V100/db-V1/db.sqlite-wal': File 'Emilie/1T-black/.DocumentRevisions-V100/db-V1/db.sqlite-wal' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.apdisk': File 'Emilie/1T-black/.apdisk' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.com.apple.timemachine.donotpresent': File 'Emilie/1T-black/.com.apple.timemachine.donotpresent' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.fcplock': File 'Emilie/1T-black/.fcplock' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.fcpuser': File 'Emilie/1T-black/.fcpuser' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/.fseventsd/fseventsd-uuid': Status can only be updated from PENDING to AVAILABLE
Failed to upload file '/o/folders/Emilie/1T-black/16045432646_5334066e3d_o.jpg': File 'Emilie/1T-black/16045432646_5334066e3d_o.jpg' exists and is identical to local copy
Failed to upload file '/o/folders/Emilie/1T-black/16070534152_20714975ac_o.jpg': File 'Emilie/1T-black/16070534152_20714975ac_o.jpg' exists and is identical to local copy
Unhandled rejection TypeError: remoteFolder.getId is not a function
    at /usr/lib/node_modules/clouddrive/lib/Node.js:924:32
    at Object.opts.onFileUpload (/usr/lib/node_modules/clouddrive/lib/Commands/UploadCommand.js:54:22)
    at /usr/lib/node_modules/clouddrive/lib/Node.js:911:17
    at /usr/lib/node_modules/clouddrive/lib/Node.js:643:24
    at /usr/lib/node_modules/clouddrive/lib/Cache/SQL.js:95:18
    at /usr/lib/node_modules/clouddrive/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/usr/lib/node_modules/clouddrive/node_modules/async/lib/async.js:236:30)
    at /usr/lib/node_modules/clouddrive/lib/Cache/SQL.js:91:22
    at tryCatcher (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/clouddrive/node_modules/knex/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

Does it mean `/o/folders/Emilie/1T-black/.fseventsd/fseventsd-uuid` was locked?

**Comment by alex-phillips** [comment]
That most likely means that it was attempting to find a parent node that doesn't exist in local cache. Run `clouddrive sync` to solve this and then upload again.

Note: you should run `sync` periodically just to keep your local cache in sync with what exists remotely. This is extremely important if you manage or use clouddrive on multiple devices.

**Comment by alex-phillips** [comment]
@pahud Is this resolved?

**Comment by pahud** [comment]
yes, thanks :-)
