### ISSUE TITLE
Error uploading new files

### ISSUE THREAD

**Issue by lanapalooza** [alex-phillips/node-clouddrive#29]
I'm running into an error when trying to upload new files. It is getting to the end of the files in one folder and then throws the below error. All the files in the folder have already been uploaded so it is just returning exists and is identical to local copy messages up until I get this error.

Unhandled rejection TypeError: remoteFolder.getId is not a function
    at /usr/local/lib/node_modules/clouddrive/dist/Node.js:1234:42
    at Object.onFileUpload (/usr/local/lib/node_modules/clouddrive/dist/Commands/UploadCommand.js:74:22)
    at /usr/local/lib/node_modules/clouddrive/dist/Node.js:1222:19
    at /usr/local/lib/node_modules/clouddrive/dist/Node.js:880:24
    at /usr/local/lib/node_modules/clouddrive/dist/Cache/SQL.js:98:18
    at /usr/local/lib/node_modules/clouddrive/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/clouddrive/node_modules/async/lib/async.js:236:30)
    at /usr/local/lib/node_modules/clouddrive/dist/Cache/SQL.js:94:22
    at tryCatcher (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/clouddrive/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)

**Comment by alex-phillips** [comment]
@lanapalooza Try and either try to run `sync` again before uploading. If that doesn't work, run `clearcache` to clear the local cache and `sync` back down. There is a folder that your cache is attempting to reference that doesn't exist locally. Probaby due to a bad DB insertion on a node creation.

**Comment by alex-phillips** [comment]
Closing this. If the problem persists, I can re-open it.

**Comment by lanapalooza** [comment]
Missed your comments in November... just tried them now and a sync didn't fix the issue on its own I had clearcache like you suggested, then run sync again and I am back to the races! Thanks for the follow-up, sorry for the delay 👍
