### ISSUE TITLE
ECONNREFUSED when a lot of downloaded files

### ISSUE THREAD

**Issue by dcromster** [alex-phillips/node-clouddrive#33]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 52.87.27.126:443
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete](net.js:1063:14)

**Comment by alex-phillips** [comment]
I assume this occurs when you attempt to download a folder recursively so it just keeps downloading files? Or is it just you repeating over and over individual download commands?

**Comment by dcromster** [comment]
Yes, I'm trying to download a folders with files. Like '/Kids video/2016/January/010116/*'.

**Comment by dcromster** [comment]
I forgot to say: Ubuntu 16.04
clouddrive version: 0.4.0

**Comment by dcromster** [comment]
Got this problem again and cat bad file:
{"logref":"563515e0-907d-11e6-8c99-f3adb096dc39","message":"Token has expired","code":""}

**Comment by alex-phillips** [comment]
@dcromster Try pulling down the `file-logging` branch. Install that and let me know if the issue persists. I have a lot of fixes in there that I'm going to merge into the next release.

**Comment by alex-phillips** [comment]
@dcromster Also, are you using your own credentials or the built in authorization?

**Comment by dcromster** [comment]
ok. I'll try to catch error.

Sorry, I did'n understand question. I did email config, init, sync.

In file-logging branch when I run sync command got this:
Syncing... ⠇Unhandled rejection SyntaxError: Unexpected end of input
    at Object.parse (native)GTFabv4FeiITebpoFmIlfb85ip4U0WtnexHxULK_9qXjbTkRBF8DW9_WxFMXgLG2Z8RsNpcRNDroWHgUboXVB8gYsRMVEtYuk4uVOrPMcd3oUw","token_type":"bearer","expires_in":3600}
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/dist/Account.js:543:23
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/async/lib/async.js:181:20
    at iterate (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/async/lib/async.js:262:13)
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/async/lib/async.js:274:29
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/async/lib/async.js:44:16
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/dist/Account.js:570:13
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/dist/Account.js:506:28
    at /home/rom/Документы/Проекты/Не мои/node-clouddrive/dist/Cache/SQL.js:184:13
    at tryCatcher (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate](/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/bluebird/js/main/async.js:15:14)

**Comment by dcromster** [comment]
Ok. I did sync and then try to download:

uncaughtException: Response code 401 (Unauthorized) date=Sat Nov 05 2016 14:52:39 GMT+0300 (MSK), pid=19076, uid=1000, gid=1000, cwd=/home/rom/Документы/Проекты/Не мои/node-clouddrive/bin, execPath=/usr/bin/nodejs, version=v4.2.6, argv=[/usr/bin/nodejs, /home/rom/Документы/Проекты/Не мои/node-clouddrive/bin/clouddrive, download, /Архив видео/2014/, /tmp], rss=57376768, heapTotal=22875744, heapUsed=16154144, loadavg=[1.212890625, 1.08740234375, 1.22802734375], uptime=71329, trace=[column=24, file=мои/node-clouddrive/node_modules/got/index.js, function=EventEmitter.<anonymous> (/home/rom/Документы/Проекты/Не, line=178, method=<anonymous> (/home/rom/Документы/Проекты/Не, native=false, column=13, file=events.js, function=emitOne, line=77, method=null, native=false, column=7, file=events.js, function=EventEmitter.emit, line=169, method=emit, native=false, column=8, file=мои/node-clouddrive/node_modules/got/index.js, function=Immediate._onImmediate (/home/rom/Документы/Проекты/Не, line=58, method=_onImmediate (/home/rom/Документы/Проекты/Не, native=false, column=17, file=timers.js, function=processImmediate [as _immediateCallback], line=383, method=null, native=false], stack=[HTTPError: Response code 401 (Unauthorized),     at EventEmitter.<anonymous> (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/got/index.js:178:24),     at emitOne (events.js:77:13),     at EventEmitter.emit (events.js:169:7),     at Immediate._onImmediate (/home/rom/Документы/Проекты/Не мои/node-clouddrive/node_modules/got/index.js:58:8),     at processImmediate [as _immediateCallback](timers.js:383:17)]
Successfully downloaded '/tmp/2014/Февраль/file.MTS'

And in this file.MTS: EXIT=EOF

**Comment by alex-phillips** [comment]
It looks like the token is expiring in between file downloads. If you can update and re-run this tes twith `-vvv` flags, let me know the output.
