### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by dcromster** [alex-phillips/node-clouddrive#52]
Hello!

In version 0.4.0 just got this:

```
undefined:1
<!DOCTYPE html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at Request._callback (/usr/local/lib/node_modules/clouddrive/dist/Account.js:352:30)
    at Request.self.callback (/usr/local/lib/node_modules/clouddrive/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/clouddrive/node_modules/request/request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/clouddrive/node_modules/request/request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

```

Node v6.11.0

**Comment by alex-phillips** [comment]
I'm updating the README now, but sadly Amazon has discontinued its unlimited service and with it, the v1 API. I wish I had a better solution, but this project is effectively dead.

**Comment by dcromster** [comment]
Oh, nooooooooo!
:(
